module.exports = hentai = {
  bookOn: true,
  name: "hentai",
  id: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
  card: [
    "Yura Kawada",
    "Hana Mitsui",
    "Byakuya Rinne",
    "Kisara Himeno",
    "Akane",
    "Shirakawa Ayane",
    "Reo Kawamura",
    "Airi Akitsuki",
    "Fujino Shion",
    "Tenka Adachi",
  ],
  anime: [
    "Futari Ecchi",
    "Baka Na Imouto O Rikou Ni Suru No Wa Ore No XX Dake Na Ken Ni Tsuite",
    "Euphoria",
    "Eroge! H mo Game Mo Kaihatsu Zanmai",
    "Otoko no Ko Delivery",
    "Overflow",
    "Sono Hanabira ni Kuchizuke wo: Anata to Koibito Tsunagi",
    "Oni Chichi",
    "Hatsu Inu",
    "Shoujo Ramune",
  ],
  cardURL: [
    "/Yura_Kawada.png",
    "/Hana_Mitsui.png",
    "/Byakuya_Rinne.png",
    "/Kisara_Himeno.png",
    "/Akane.png",
    "/Shirakawa_Ayane.png",
    "/Reo_Kawamura.png",
    "/Airi_Akitsuki.png",
    "/Fujino_Shion.png",
    "/Tenka_Adachi.png",
  ],
  typeRare: [
    "[R]",
    "[R]",
    "[SR]",
    "[R]",
    "[SR]",
    "[R]",
    "[SR]",
    "[UR]",
    "[R]",
    "[R]",
  ],
  date: new Date(),
};
