module.exports = ecchi = {
  bookOn: true,
  name: "Ecchi",
  id: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
  card: [
    "Ui Wakana.png",
    "Moka Akashiya",
    "Chocolate",
    "Ako Suminoe",
    "Chizuru Minamoto",
    "Crimvael",
    "Ayame Kajou",
    "Konjiki no Yami",
    "Himari Noihara",
    "Saeko Busujima",
  ],
  anime: [
    "Okusama ga Seitokaichou",
    "Rosario + Vampire",
    "Nekopara!",
    "Kiss x Sis",
    "Kanakon",
    "Ishuzoku Reviewers",
    "Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai",
    "To Love-ru",
    "Omamori Himari",
    "High School of The Dead",
  ],
  cardURL: [
    "/Ui_Wakana.png",
    "/Moka_Akashiya.png",
    "/Chocolate.png",
    "/Ako_Suminoe.png",
    "/Chizuru_Minamoto.png",
    "/Crimvael.png",
    "/Ayame_Kajou.png",
    "/Konjiki_no_Yami.png",
    "/Himari_Noihara.png",
    "/Saeko_Busujima.png",
  ],
  typeRare: [
    "[R]",
    "[R]",
    "[SR]",
    "[R]",
    "[SR]",
    "[R]",
    "[SR]",
    "[UR]",
    "[R]",
    "[R]",
  ],
  date: new Date().getTime(),
};
