module.exports = mahouShoujo = {
  bookOn: true,
  name: "mahoushoujo",
  id: [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
  card: [
    "Nagisa Misumi",
    "Hanato Kobato",
    "Koyuki Himekawa",
    "Hinamori Amu",
    "Nanoha Takamachi",
    "Usagi Tsukino",
    "Madoka Kaname",
    "Sakura Kinomoto",
    "Aya Asagiri",
    "Ichigo Monami",
  ],
  anime: [
    "Futari wa Precure",
    "Kobato",
    "Mahou Shoujo Ikusei Keikaku",
    "Shugo Chara",
    "Mahou Shoujo Lyrical Nanoha",
    "Seilor Moon",
    "Mahou Shoujo Madoka Magica",
    "Cardcaptor Sakura",
    "Mahou Shoujo Site",
    "Tokyo New New",
  ],
  cardURL: [
    "/Nagisa_Misumi.png",
    "/Hanato_Kobato.png",
    "/Koyuki_Himekawa.png",
    "/Hinamori_Amu.png",
    "/Nanoha_Takamachi.png",
    "/Usagi_Tsukino.png",
    "/Madoka_Kaname.png",
    "/Sakura_Kinamoto.png",
    "/Aya_Asagiri.png",
    "/Ichigo_Monami.png",
  ],
  typeRare: [
    "[R]",
    "[R]",
    "[SR]",
    "[R]",
    "[SR]",
    "[R]",
    "[SR]",
    "[UR]",
    "[R]",
    "[R]",
  ],
  date: new Date(),
};
