module.exports = trap = {
  bookOn: true,
  name: "Trap",
  id: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
  card: [
    "Luka Urushibara",
    "Gasper Vladi",
    "Hideri Kanzaki",
    "Saika Totsuka",
    "Felix Argyle",
    "Earl Ciel Phantomhive",
    "Arikawa Hime",
    "Astolfo",
    "Hideyoshi Kinoshita",
    "Nagisa Shiota",
  ],
  anime: [
    "Steins;Gate",
    "High School DxD",
    "Blend S",
    "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
    "Re:Zero Kara Hajimeru Isekai Seikatsu",
    "Kuroshitsuji",
    "Himegoto",
    "Fate/Grand Order",
    "Assassination Classroom",
  ],
  cardURL: [
    "/Luka_Urushibara.png",
    "/Gasper_Vladi.png",
    "/Hideri_Kanzaki.png",
    "/Saika_Totsuka.png",
    "/Felix_Argyle.png",
    "/Earl_Ciel_Phantomhive.png",
    "/Arikawa_Hime.png",
    "/Astolfo.png",
    "/Hideyoshi_Kinoshita.png",
    "/Nagisa_Shiota.png",
  ],
  typeRare: [
    "[R]",
    "[R]",
    "[SR]",
    "[R]",
    "[SR]",
    "[R]",
    "[SR]",
    "[UR]",
    "[R]",
    "[R]",
  ],
  date: new Date().getTime(),
};
